name: Build Image

on:
  push:
    tags:
      - "*"

jobs:
  build:
    uses: ubio/github-actions/.github/workflows/ci-build.yaml@master
    with:
      name: NodeScript Fetch Adapter
      image: gcr.io/automation-cloud-registry/nodescript-adapter-fetch
      ref: ${{ github.ref }}
      file: Dockerfile
    secrets:
      REGISTRY_SECRET: ${{ secrets.GCP_REGISTRY_ACCESS }}
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}

  deploy-fetch:
    needs: build
    uses: ubio/github-actions/.github/workflows/cd-dispatch.yaml@master
    with:
      event_name: built-nodescript-adapter-fetch
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
