name: Deploy

on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed

jobs:
  deploy-production:
    needs: build
    uses: ubio/github-actions/.github/workflows/cd-dispatch-deploy.yaml@master
    with:
      gh_user: NodeScriptLang
      gh_repo: infrastructure
      image_name: nodescript-fetch-service
      env_name: production
      app_path: apps/fetch-service
      auto_merge: false
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
